apiVersion: v1
stringData:
  credentials: |-
    {{- if .Values.oidc.customer.providers }}
    {{- range .Values.oidc.customer.providers }}
    - name: {{ .name | quote }}
      owner: customer
      credentials:
        {{- .credentials | nindent 8 }}
    {{- end }}
    {{- end }}
    {{- if .Values.oidc.giantswarm.providers }}
    {{- range .Values.oidc.giantswarm.providers }}
    - name: {{ .name | quote }}
      owner: giantswarm
      credentials:
        {{- .credentials | nindent 8 }}
    {{- end }}
    {{- end }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque
