apiVersion: v1
stringData:
  credentials: |-
    - name: mock
      owner: giantswarm
      credentials:
        azure_access_key_id: {{ .Values.idp.azure.accessKeyID | quote }}
        azure_secret_access_key: {{ .Values.idp.azure.secretAccessKey | quote }}
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-credentials
  namespace: {{ include "resource.default.namespace" . }}
type: Opaque

