version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

jobs:
  tests:
    executor: architect/architect
    steps:
    - checkout
    - run:
        name: Run tests
        command: CGO_ENABLED=0 make test-all

workflows:
  build:
    jobs:
    - tests:
        filters:
          tags:
            only: /^v.*/
    - architect/go-build:
        context: architect
        name: go-build
        binary: dex-operator
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/
    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        executor: app-build-suite
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: dex-operator
        requires:
        - push-to-registries
        filters:
            # Trigger the job also on git tag.
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
