version: 2.1

orbs:
  architect: giantswarm/architect@4.24.0

jobs:
  tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run tests"
          command: CGO_ENABLED=0 make test

workflows:
  build:
    jobs:
    - tests:
        filters:
          tags:
            only: /^v.*/
    - architect/go-build:
        context: architect
        name: go-build
        binary: dex-operator
        resource_class: xlarge
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-docker:
        context: architect
        name: push-dex-operator-to-quay
        image: "quay.io/giantswarm/dex-operator"
        username_envar: "QUAY_USERNAME"
        password_envar: "QUAY_PASSWORD"
        requires:
        - go-build
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/
    - architect/push-to-docker:
          context: "architect"
          name: push-dex-operator-to-docker
          image: "docker.io/giantswarm/dex-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

    # Ensure that for every commit
    # there is an app version in the test catalog.
    - architect/push-to-app-catalog:
        context: architect
        name: push-to-app-catalog
        app_catalog: "control-plane-catalog"
        app_catalog_test: "control-plane-test-catalog"
        chart: "dex-operator"
        requires:
        - push-dex-operator-to-quay
        - push-dex-operator-to-docker
        filters:
          # Trigger the job also on git tag.
          tags:
            only: /^v.*/

# Disable collection updates temporarily to not break anything mistakenly
#     - architect/push-to-app-collection:
#         context: architect
#         name: push-to-openstack-app-collection
#         app_name: "dex-operator"
#         app_collection_repo: "openstack-app-collection"
#         requires:
#         - push-to-app-catalog
#         filters:
#           branches:
#             ignore: /.*/
#           tags:
#             only: /^v.*/
